---
apiVersion: v1
kind: ImageStream
metadata:
  name: s2i-gulp-httpd24
  creationTimestamp: null
  annotations:
    openshift.io/display-name: Gulp
spec:
  tags:
    - name: latest
      annotations:
        openshift.io/display-name: Gulp
        description: >-
          Build and run Gulp 6+ apps based on the official
          centos/httpd-24-centos7 image. For more information about using this
          builder image, see https://github.com/EnilPajic/s2i-angular-httpd24.
        iconClass: icon-js
        tags: 'builder,gulp,javascript'
        supports: 'angular'
      from:
        kind: DockerImage
        name: 'mprahl/s2i-gulp-httpd24:latest'
